Add some companies
filhodanuvem/awesome-php-jobs pull request #32
Opened 2020-10-02 10:29 UTC by jonathanpereira

Cheers,

I've added: Altran, Tequila Rapido and Zizoo.

=)

2020-10-02 19:23 UTC, filhodanuvem requested changes

2020-10-02 19:23 UTC, filhodanuvem commented on README.md
> +* [Tequila Rapido](https://www.welcometothejungle.com/fr/companies/tequilarapido/jobs) | Nice, France
Acho que Tequila vem antes de TicketSwap 😅 
Alias eu preciso fazer um CI verificar isso haha.

2020-10-02 19:47 UTC, jeanpimentel commented on README.md
> +* [Tequila Rapido](https://www.welcometothejungle.com/fr/companies/tequilarapido/jobs) | Nice, France
Cadastrei uma issue pra isso.

2020-10-02 19:58 UTC, jonathanpereira commented on README.md
> +* [Tequila Rapido](https://www.welcometothejungle.com/fr/companies/tequilarapido/jobs) | Nice, France
Feito! hehe!

2020-10-03 12:55 UTC, merged

2020-10-03 12:56 UTC, filhodanuvem commented
Valeu @jonathanpereira 🇫🇷